#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
PREZTO_INIT_CMD="${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
if [ -s $PREZTO_INIT_CMD ]; then
  source $PREZTO_INIT_CMD
fi

# Customize to your needs...
export HISTFILE=~/.zsh_history
export HISTSIZE=100000
export SAVEHIST=100000
setopt nobeep
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# Vim
alias vi="vim"

# Java
JAVA_HOME_CMD=/usr/libexec/java_home
if [ -s $JAVA_HOME_CMD ]; then
  JAVA_VERSION=1.6
  JAVA_HOME=$($JAVA_HOME_CMD -v $JAVA_VERSION)
fi

# Android
export ANDROID_HOME=`brew --prefix`/opt/android-sdk

# Git
GIT_CONTRIB_HOME=`brew --prefix`/share/git-core/contrib
alias ggr='git log --graph --date-order -C -M --pretty=format:"<%h> %ad [%an] %Cgreen%d%Creset %s" --all --date=short'

# Python
VIRTUALENVWRAPPER_CMD=`brew --prefix`/bin/virtualenvwrapper.sh
if [ -s $VIRTUALENVWRAPPER_CMD ]; then
  VIRTUALENVWRAPPER_PYTHON=`brew --prefix`/bin/python3.4
  . $VIRTUALENVWRAPPER_CMD
fi

# Ruby
RUBY_HOME=`brew --cellar`/ruby/2.1.2

# Groovy
export GROOVY_HOME=/usr/local/opt/groovy/libexec

# node
NVM_CMD=`brew --prefix nvm`/nvm.sh
if [ -s $NVM_CMD ]; then
  . $NVM_CMD
fi

# Global
export GTAGSCONF=/usr/local/share/gtags/gtags.conf
export GTAGSLABEL=pygments

# Z
Z_CMD=`brew --prefix`/etc/profile.d/z.sh
if [ -s $Z_CMD ]; then
  . `brew --prefix`/etc/profile.d/z.sh
fi

# PATH
PATH=$JAVA_HOME/bin:`brew --prefix`/bin:$GIT_CONTRIB_HOME/workdir:$RUBY_HOME/bin:$PATH
export PATH
